const CATALOG_URL = "catalog.json";
const tg = window.Telegram?.WebApp || null;
const $ = id => document.getElementById(id);
const els = {grid:$('grid'),status:$('status'),search:$('searchInput'),type:$('typeSelect'),sort:$('sortSelect'),error:$('errorBox'),retry:$('retryBtn'),player:$('playerPanel'),catalog:$('catalogSection'),frame:$('playerFrame'),movieTitle:$('playerMovieTitle'),movieMeta:$('playerMovieMeta'),loadMore:$('loadMoreBtn'),closeAll:$('closeAllBtn'),closePlayer:$('closePlayerBtn'),favorites:$('favoritesBtn')};
let allItems=[], filteredItems=[], visibleCount=12, activeFilter='all';
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function normalize(x={}){return {title:String(x.title||'Sin título'),type:String(x.type||'Sin categoría'),year:Number(x.year)||'',description:String(x.description||'Sin descripción'),poster_url:String(x.poster_url||x.posterurl||''),video_url:String(x.video_url||x.videourl||'').trim(),trailer_url:String(x.trailer_url||x.trailerurl||x.trailerembedurl||'').trim(),is_featured:Boolean(x.is_featured??x.isfeatured),tmdbid:x.tmdbid||x.id||null};}
function favorites(){try{return JSON.parse(localStorage.getItem('favorites')||'[]')}catch{return[]}}
function isFav(item){return favorites().includes(String(item.tmdbid||item.title))}
function toggleFav(item){let f=favorites(),id=String(item.tmdbid||item.title);f=f.includes(id)?f.filter(x=>x!==id):[...f,id];localStorage.setItem('favorites',JSON.stringify(f));renderGrid();}
function cardHtml(item,index){const fav=isFav(item);return `<article class="card" tabindex="0" role="button" aria-expanded="false" data-index="${index}"><img class="poster" src="${esc(item.poster_url)}" alt="${esc(item.title)}" loading="lazy"><div class="card-body"><h3 class="title">${esc(item.title)}</h3><div class="meta"><span>${esc(item.year)}</span>${item.is_featured?'<span class="badge">Destacada</span>':''}<span>${esc(item.type)}</span></div></div><div class="extra"><p><strong>Género:</strong> ${esc(item.type)}</p><p><strong>Año:</strong> ${esc(item.year)}</p><p>${esc(item.description)}</p></div><div class="card-actions"><button class="play-btn" data-action="play">${item.video_url?'Ver peli':'Ver tráiler'}</button><button class="favorite-btn ${fav?'is-favorite':''}" data-action="favorite">${fav?'★ En favoritos':'☆ Añadir a favoritos'}</button><button class="less-btn" data-action="less">Ver menos</button></div></article>`}
function renderGrid(){const items=filteredItems.slice(0,visibleCount);els.grid.innerHTML=items.map(cardHtml).join('');els.status.textContent=filteredItems.length?`Mostrando ${items.length} de ${filteredItems.length} títulos`:'No hay resultados';els.loadMore.hidden=visibleCount>=filteredItems.length;els.grid.querySelectorAll('.poster').forEach(img=>img.addEventListener('error',()=>{const d=document.createElement('div');d.className='poster-fallback';d.textContent=img.alt;img.replaceWith(d)}));els.grid.querySelectorAll('.card').forEach(card=>{const item=filteredItems[Number(card.dataset.index)];card.addEventListener('click',e=>{if(!e.target.closest('[data-action]'))toggleCard(card)});card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggleCard(card)}});card.querySelector('[data-action="play"]').addEventListener('click',e=>{e.stopPropagation();openPlayer(item)});card.querySelector('[data-action="favorite"]').addEventListener('click',e=>{e.stopPropagation();toggleFav(item)});card.querySelector('[data-action="less"]').addEventListener('click',e=>{e.stopPropagation();card.classList.remove('expanded');card.setAttribute('aria-expanded','false')})})}
function toggleCard(c){document.querySelectorAll('.card.expanded').forEach(x=>{if(x!==c){x.classList.remove('expanded');x.setAttribute('aria-expanded','false')}});const open=!c.classList.contains('expanded');c.classList.toggle('expanded',open);c.setAttribute('aria-expanded',String(open))}
function provider(u){try{const h=new URL(u).hostname.replace('www.','');return h.includes('youtube')||h==='youtu.be'?'youtube':h.includes('dailymotion')||h==='dai.ly'?'dailymotion':h.includes('vimeo')?'vimeo':'generic'}catch{return'generic'}}
function playable(u){u=String(u||'').trim();if(!u)return'';const p=provider(u);if(p==='youtube'){if(/^[\w-]{11}$/.test(u))return`https://www.youtube.com/embed/${u}`;const m=u.match(/(?:v=|youtu\.be\/|shorts\/|embed\/)([\w-]{6,})/);return m?`https://www.youtube.com/embed/${m[1]}`:u}if(p==='vimeo'){const m=u.match(/vimeo\.com\/(?:video\/)?(\d+)/);return m?`https://player.vimeo.com/video/${m[1]}`:u}if(p==='dailymotion'){const m=u.match(/(?:video\/|dai\.ly\/)([\w]+)/);return m?`https://geo.dailymotion.com/player.html?video=${m[1]}`:u}return u}
function openPlayer(item){const raw=item.video_url||item.trailer_url, src=playable(raw);if(!src){alert('Esta entrada no tiene una URL configurada.');return}localStorage.setItem('lastMovie',JSON.stringify(item));els.movieTitle.textContent=item.title;els.movieMeta.textContent=`${item.type}${item.year?' · '+item.year:''}${item.video_url?'':' · tráiler'}`;els.frame.src=src;els.player.classList.add('active');els.catalog.hidden=true;window.scrollTo({top:0,behavior:'smooth'})}
function closePlayer(){els.frame.src='about:blank';els.player.classList.remove('active');els.catalog.hidden=false}
function applyFilters(){const q=els.search.value.trim().toLowerCase();localStorage.setItem('lastSearch',els.search.value);localStorage.setItem('lastType',els.type.value);let x=[...allItems];if(activeFilter==='featured')x=x.filter(i=>i.is_featured);if(activeFilter==='favorites')x=x.filter(isFav);if(q)x=x.filter(i=>[i.title,i.type,i.year,i.description].some(v=>String(v).toLowerCase().includes(q)));if(els.type.value!=='Todo')x=x.filter(i=>i.type.toLowerCase()===els.type.value.toLowerCase());if(els.sort.value==='recent')x.sort((a,b)=>Number(b.year||0)-Number(a.year||0));if(els.sort.value==='alpha')x.sort((a,b)=>a.title.localeCompare(b.title,'es'));filteredItems=x;visibleCount=12;renderGrid()}
async function loadCatalog(){els.error.hidden=true;els.status.textContent='Cargando catálogo...';try{const r=await fetch(`${CATALOG_URL}?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();const list=Array.isArray(d)?d:(Array.isArray(d.movies)?d.movies:[]);allItems=list.map(normalize);applyFilters()}catch(e){console.error(e);els.status.textContent='';els.error.hidden=false;els.loadMore.hidden=true}}
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;applyFilters()}));els.search.value=localStorage.getItem('lastSearch')||'';els.type.value=localStorage.getItem('lastType')||'Todo';els.search.addEventListener('input',applyFilters);els.type.addEventListener('change',applyFilters);els.sort.addEventListener('change',applyFilters);els.retry.addEventListener('click',loadCatalog);els.loadMore.addEventListener('click',()=>{visibleCount+=12;renderGrid()});els.closeAll.addEventListener('click',()=>document.querySelectorAll('.card.expanded').forEach(c=>{c.classList.remove('expanded');c.setAttribute('aria-expanded','false')}));els.closePlayer.addEventListener('click',closePlayer);els.favorites.addEventListener('click',()=>{activeFilter='favorites';document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x.dataset.filter==='favorites'));applyFilters()});tg?.ready();tg?.expand?.();$('userLabel').textContent=tg?'Dentro de Telegram':'Navegador';$('modeChip').textContent=tg?'Telegram WebApp':'Modo web';loadCatalog();
